name: Update CF ProxyIP

on:
  # 注释掉下面 schedule 可取消定时
   schedule:
     - cron: "15 */3 * * *"  # 每3小时执行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install aiohttp requests
      - name: Run update script
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          REGIONS_JSON: ${{ secrets.REGIONS_JSON }}
        run: python main.py
